name: JobBridge CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Security scan with npm audit
        run: npm audit --audit-level=moderate || true

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: jobbridge.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t jobbridge.azurecr.io/jobbridge:${{ github.sha }} .

      - name: Push Docker image
        run: docker push jobbridge.azurecr.io/jobbridge:${{ github.sha }}

      - name: Container Image Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jobbridge.azurecr.io/jobbridge:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Azure WebApp Deploy (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: jobbridge-webapp
          images: jobbridge.azurecr.io/jobbridge:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}


          