name: JobBridge CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Security scan with npm audit
        run: npm audit --audit-level=moderate || true

      - name: Log in to Azure Container Registry
        run: az acr login --name jobbridge

      - name: Build Docker image
        run: docker build -t jobbridge.azurecr.io/jobbridge:${{ github.sha }} .

      - name: Push Docker image
        run: docker push jobbridge.azurecr.io/jobbridge:${{ github.sha }}

      - name: Container Image Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jobbridge.azurecr.io/jobbridge:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Azure WebApp Deploy (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: jobbridge-webapp
          slot-name: staging
          images: jobbridge.azurecr.io/jobbridge:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_STAGING_PUBLISH_PROFILE }}

      - name: Azure WebApp Deploy (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: jobbridge-webapp
          slot-name: production
          images: jobbridge.azurecr.io/jobbridge:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
